### PR TITLE
fixed fixing css pathes in asset merger if core is not installed in a subdirectory, fixed #3280

### LINKED ISSUE #3280: css icons not visible in zk1.4.4build182
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4build182
| PHP Version       | 5.6.26

### Expected behavior
Display CSS images

### Actual behavior
CSS images like `class="z-icon-es-view"` are not visible any longer. Saw this in News headline. It does look like this:
news-no-css-icons

But should looks like this:
news-with-css-icons

### Steps to reproduce
- install zk1.4.4build182
- install/activate News module and/or Contnet
- access ?module=news&type=user&func=view and check news nav-bar
- tested with Bootstrap & Andreas08 theme

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #3280 
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Todos
- [ ] Tests

### CODE REVIEW

File: src/system/ThemeModule/Engine/Asset/Merger.php [hunk 1]
```diff
@@ -274,7 +274,7 @@ private function cssFixPath($line, $relativeFilePath)
                 $depth = substr_count($match[1], '../') * -1;
                 $path = $depth < 0 ? array_slice($relativeFilePath, 0, $depth) : $relativeFilePath;
                 $path = implode('/', $path);
-                $path = !empty($path) ? $path . '/' : '';
+                $path = !empty($path) ? $path . '/' : '/';
```
Comment (craigh) [inline src/system/ThemeModule/Engine/Asset/Merger.php]: fyi - this code was copied right out of the old asset combination methods.

Comment (craigh) [inline src/system/ThemeModule/Engine/Asset/Merger.php]: https://github.com/zikula/core/blob/4a1935fb0f8fed18738fda32054e311292248d8e/src/lib/legacy/util/JCSSUtil.php#L797-L797
