### PR TITLE
fixed DateTime construction, fixed #3091

### LINKED ISSUE #3091: edit page spits error: DateTime::__construct(): Failed to parse time string (1475140867) at position 7 (8): Unexpected character
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.25
| Content              | 4.2.1

Follow-up ticket of: **[Content Tracker: #173](https://github.com/zikula-modules/Content/issues/173)**.
### Expected behavior
Properly edit page

### Actual behavior
receiving error 500 with message:

`DateTime::__construct(): Failed to parse time string (1475140867) at position 7 (8): Unexpected character`

Stack trace:

```
Stack Trace
in system/PageLockModule/Api/LockingApi.php at line 211   -
            // create the new object
            $newLock = new PageLockEntity();
            $newLock->setName($lockName);
            $newLock->setCdate(new \DateTime($now));
            $newLock->setEdate($expireDate);
            $newLock->setSession($theSessionId);
            $newLock->setTitle($lockedByTitle);
at DateTime ->__construct ('1475140867') 
in system/PageLockModule/Api/LockingApi.php at line 211   + 
at LockingApi ->requireLock ('contentPage2', 's.waitz', '62.96.145.145') 
in system/PageLockModule/Api/LockingApi.php at line 143   + 
at LockingApi ->addLock ('contentPage2', 'http://staging.amc-idstein.de/index.php?module=content&type=admin&func=main', false) 
in system/PageLockModule/Api/UserApi.php at line 44   + 
at UserApi ->pageLock (array('lockName' => 'contentPage2', 'returnUrl' => 'http://staging.amc-idstein.de/index.php?module=content&type=admin&func=main')) 
at call_user_func (array(object(UserApi), 'pageLock'), array('lockName' => 'contentPage2', 'returnUrl' => 'http://staging.amc-idstein.de/index.php?module=content&type=admin&func=main')) 
in lib/util/ModUtil.php at line 1222   + 
at ModUtil ::exec ('PageLock', 'user', 'pageLock', array('lockName' => 'contentPage2', 'returnUrl' => 'http://staging.amc-idstein.de/index.php?module=content&type=admin&func=main'), true, null) 
in lib/util/ModUtil.php at line 1298   + 
at ModUtil ::apiFunc ('PageLock', 'user', 'pageLock', array('lockName' => 'contentPage2', 'returnUrl' => 'http://staging.amc-idstein.de/index.php?module=content&type=admin&func=main')) 
in modules/Content/lib/Content/Form/Handler/Admin/EditPage.php at line 78   + 
at Content_Form_Handler_Admin_EditPage ->initialize (object(Zikula_Form_View)) 
in lib/legacy/Zikula/Form/View.php at line 283   + 
at Zikula_Form_View ->execute ('admin/editpage.tpl', object(Content_Form_Handler_Admin_EditPage)) 
in modules/Content/lib/Content/Controller/Admin.php at line 54   + 
at Content_Controller_Admin ->editpage (array('pid' => '2')) 
at call_user_func_array (array(object(Content_Controller_Admin), 'editPage'), array(array('pid' => '2'))) 
in lib/legacy/Zikula/AbstractController.php at line 153   + 
at Zikula_AbstractController ->__call ('editPageAction', array(array('pid' => '2'))) 
at Content_Controller_Admin ->editPageAction (array('pid' => '2')) 
at call_user_func (array(object(Content_Controller_Admin), 'editPageAction'), array('pid' => '2')) 
in lib/util/ModUtil.php at line 1222   + 
at ModUtil ::exec ('Content', 'admin', 'editPage', array('pid' => '2'), false, null) 
in lib/util/ModUtil.php at line 1272   + 
at ModUtil ::func ('Content', 'admin', 'editPage', array('pid' => '2')) 
in lib/Zikula/Bundle/CoreBundle/Controller/LegacyController.php at line 176   + 
at LegacyController ->getLegacyResponse ('Content', 'admin', 'editPage', array('pid' => '2'), false) 
in lib/Zikula/Bundle/CoreBundle/Controller/LegacyController.php at line 90   + 
at LegacyController ->legacyAction (object(Zikula_Request_Http)) 
at call_user_func_array (array(object(LegacyController), 'legacyAction'), array(object(Zikula_Request_Http))) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 144   + 
at HttpKernel ->handleRaw (object(Zikula_Request_Http), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 64   + 
at HttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   + 
at ContainerAwareHttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185   + 
at Kernel ->handle (object(Zikula_Request_Http)) 
in index.php at line 23   + 
```

### Steps to reproduce
- install ZK 1.4.3
- install Content master branch snapshot
click "edit page" of sample content page

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #3091 
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

### CODE REVIEW

File: src/system/PageLockModule/Api/LockingApi.php [hunk 1]
```diff
@@ -205,10 +205,13 @@ public function requireLock($lockName, $lockedByTitle, $lockedByIPNo, $sessionId
...
             $this->repository->updateExpireDate($lockName, $theSessionId, $expireDate);
         } else {
+            $createdDate = new \DateTime();
+            $createdDate->setTimestamp($now);
+
             // create the new object
             $newLock = new PageLockEntity();
             $newLock->setName($lockName);
-            $newLock->setCdate(new \DateTime($now));
+            $newLock->setCdate($createdDate);
```
Comment (cmfcmf) [inline src/system/PageLockModule/Api/LockingApi.php]: Why don't you just use `->setCdate(new \DateTime());`?

Comment (Guite) [inline src/system/PageLockModule/Api/LockingApi.php]: Because I seem dumb today ;-) Changed.
