### PR TITLE
restrict ability to register same email with different auth methods

### LINKED ISSUE #3720: Duplicate emails are allowed
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 248
| PHP Version       | 5.6

### Expected behavior
If an email address is allready registered another usershould not be able to use the same one. This is also valid even if the user is registering with different authentication methods

### Actual behavior
a user (me) is registered with an email via ZAuth. With the same email address I am registered at facebook. If I now register via facebook/oauth it is possible without any problem. I looked into the database and can see both users do have the same email address

### Steps to reproduce
see actual behavior

Is it a bug or is it a feature?

### PR DESCRIPTION
**Pull request by craigh**
closes #3720
refs #4197

### CODE REVIEW

File: src/system/UsersModule/Controller/RegistrationController.php [hunk 1]
```diff
@@ -161,11 +163,21 @@ public function registerAction(
...
+                        /** @var ConstraintViolationInterface $validationError */
                         foreach ($validationErrors as $validationError) {
                             $this->addFlash('error', $validationError->getMessage());
+                            $codes[] = $validationError->getCode();
+                        }
+                        if ($authenticationMethod instanceof ReEntrantAuthenticationMethodInterface) {
+                            $session->remove('authenticationMethod');
+                        }
+                        $route = 'zikulausersmodule_registration_register';
+                        if (in_array(ValidUserFieldsValidator::DUP_EMAIL_ALT_AUTH, $codes)) {
```
Comment (Guite) [inline src/system/UsersModule/Controller/RegistrationController.php:176]: Please add `true` as third parameter.

File: src/system/UsersModule/Entity/Repository/UserRepository.php [hunk 2]
```diff
@@ -217,4 +217,35 @@ public function searchActiveUser(array $unameFilter = [])
 
         return $this->query($filter, ['uname' => 'asc']);
     }
+
+    public function countDuplicateUnames(string $uname, ?int $uid = null): int
+    {
+        $qb = $this->createQueryBuilder('u');
+        $qb->select('count(u.uid)')
+            ->where($qb->expr()->eq('LOWER(u.uname)', ':uname'))
+            ->setParameter('uname', $uname);
```
Comment (Guite) [inline src/system/UsersModule/Entity/Repository/UserRepository.php:226]: `strtolower($uname)`?

**Comment by Guite** [comment]
`MockUserRepository` needs to implement the two new methods (see Travis).
